name: Build Docker Compose Services

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.parse-changes.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files
        id: detect
        uses: tj-actions/changed-files@v45.0.4
        with:
          files: |
            database/**
            kb/**
            data-processing/**
            api/**
            rag/**
            gui-panel/**
            kpi-engine/**

      - name: Parse changed services
        id: parse-changes
        run: |
          # Lista delle cartelle dei servizi
          services="database kb data-processing api rag gui-panel kpi-engine"
          changed_services=""
          for service in $services; do
            if [[ "${{ steps.detect.outputs.all_changed_files }}" == *"$service/"* ]]; then
              changed_services="$changed_services $service"
            fi
          done
          echo "Changed services: $changed_services"
          echo "::set-output name=changed::$changed_services"

  print-changed-containers:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Print changed containers
        run: |
          echo "Containers to be rebuilt: ${{ needs.detect-changes.outputs.changed-services }}"

  build-database:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changed-services, 'database')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push database container
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/smartfactory/db-init:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build-containers:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [kb, data-processing, api, rag, gui-panel, kpi-engine]

    steps:
      - name: Skip job if service not changed
        run: |
          if [[ ! "${{ needs.detect-changes.outputs.changed-services }}" =~ "${{ matrix.service }}" ]]; then
            echo "::skip-job::"
          fi
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/smartfactory/${{ matrix.service }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
