name: Build and Test Docker Compose Services

on:
  push:
    branches:
      - main

jobs:
  build-db-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
  
      - name: Build and cache Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/smartfactory/db-init:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build-topic-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [kb, data-processing, api, rag, gui-panel, kpi-engine]  # Replace with your actual service names

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and cache Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/smartfactory/${{ matrix.service }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64